### ISSUE TITLE
Treat black ox statue as an offtank

### ISSUE THREAD

**Issue by villiansv** [Luxocracy/TidyPlatesContinued#14]
Is it possible to have a 3rd color for mobs targeting the black ox statue? It would be really beneficial to be able to tell at a glance if a mob is targeting the tank (good), the statue (still good) or a party member (not good).

I appreciate it may be beyond the scope of this project, but thought it wouldn't hurt to ask.

**Comment by Luxocracy** [comment]
I can definitely make this be part of the offtank coloring that already exists quite easily. Adding a new color for it is also doable, but seems unnecessary since the offtank coloring already exists, unless I am missing a scenario where this is something that would be useful.

The only thing that might not be doable is to check if it is targeting **your** black ox statue specifically. I could do something like check if you have a statue active and then see if the mobs are targeting a unit named black ox statue. But there is nothing, as far as I can tell, that acts like the _pet_ UnitId where by it is specifically **your** pet.

**Comment by villiansv** [comment]
Yes, the existing offtank coloring would be great. I can't envision a scenario where it would be crucial to have a separate color for it - as long as it's easy to tell that the newly pulled adds are **not** attacking healers/dps I'll be happy.

**Comment by Luxocracy** [comment]
I've added a new release with this addition in it. It can be found [here](https://luxocracy.github.io/TidyPlatesContinued/) or [here](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.2)

**Comment by Nihylin** [comment]
Thank you SO much for that. I've been in the same situation as villiansv and secretly wished something would be done about it. You're killing it, Luxo !

**Comment by Luxocracy** [comment]
I made a change to how it gets the name of the "Black Ox Statue" so it should now work for all classes and other monks statues as well.
