### ISSUE TITLE
Hey Luxo

### ISSUE THREAD

**Issue by Apoxiosis** [Luxocracy/TidyPlatesContinued#15]
we were speaking on curse about some features, primarily displaying purgeable buffs above healthbars.

I have been noticing that as I run into new areas, healthbar names will show as "Unknown" until I target something, which then displays their names properly. 

have you seen this?

**Comment by Luxocracy** [comment]
Displaying purgeable buffs as well as enrage effects is already something that has been added.

As for the issue you described, no, I haven't come across it myself. And I would need a way to reproduce it to be able to look into it properly.

Is everything else but the name being displayed properly?

**Comment by ShizCalev** [comment]
I've experienced the "Unknown" issue too. 

Mob shows at full health with no other information beside the name "Unknown".

**Comment by Luxocracy** [comment]
I'm thinking it could have something to do with being on a high pop server and certain information not being available immediately as it normally is due to server load. The addon currently doesn't attempt to re-update if any information would happen to be missing until something about the frame changes like health, debuffs or on mouseover/target is changed.
I might be able to do something about it but I will have to look into if this is what is happening first, and what changes would have to be made to get it to update once the information is available.

**Comment by Apoxiosis** [comment]
Cool deal, I got the update. I also saw some of the latest features added. ai gotta say its great to have support for this addon again. Love what youre doing
