### ISSUE TITLE
quest icon showing on every mob in dungeons

### ISSUE THREAD

**Issue by hollo6** [Luxocracy/TidyPlatesContinued#17]
I have enabled "Show Quest Icon on Units" and it is amazing but puts the icon on every single mob in dungeons. It is very annoying, could you please remove this or make it settable?

**Comment by Luxocracy** [comment]
I have noticed this myself, but I've found it rather handy to know which mobs give % in M+ and which don't, which is why I haven't done anything about it.

But there shouldn't be any issues with adding an option for it at the very least, but then again just disabling it in dungeons is a lot easier.

**Comment by hollo6** [comment]
But it shows up in hc dungeons as well and my problem is I don't want to spend time and clicks enabling and then disabling it every time I enter/leave a dungeon, not to mention if I forget it at the start of an m+ and don't have time to clicky-click to disable it when it has already started.
An option for disabling this feature in dungeons would be awesome.

**Comment by Luxocracy** [comment]
Hmm, I haven't had it appear in anything but M+ myself, with the exception of bosses. Because last I checked mobs don't show up as an objective in heroics, so that is very odd if they are showing up with a quest icon.

So if it is showing up in heroics there might be something else going on and I'll probably just end up disabling it in dungeons all together.

**Comment by hollo6** [comment]
Thank you, I think it would be the best, especially since in m+, people who care about % already have a ton of other ways to track it.

**Comment by Luxocracy** [comment]
It should now be disabled in dungeons with the latest release.

**Comment by hollo6** [comment]
Awesome, thank you!
