### ISSUE TITLE
A Couple of Issues

### ISSUE THREAD

**Issue by Legitheals** [Luxocracy/TidyPlatesContinued#19]
First issue: Even though I have 'exclude instances' unchecked, tidyplates nameplates aren't showing up in dungeons, but will show up in the world and in battlegrounds. 

Second issue: [https://puu.sh/BvnRb/7df583c5d6.png](url) are the small green bars with names on them part of this addon? I can't find an option relating to it anywhere.

**Comment by Luxocracy** [comment]
For you first issue: Are you talking about friendly nameplates? Because if you are there is nothing I can do about it since Blizzard has limited this functionality in dungeons.

Second: Yes, this is called the "Tug-o-Threat Indicator". I've noticed it isn't exactly positioned well for a large portion of the themes and looks generally out of place in all of them.

**Comment by Legitheals** [comment]
First, yes. That is unfortunate.

Second: Thanks, this was bothering me for a while.
