### ISSUE TITLE
"Unknown" Issue Persisting

### ISSUE THREAD

**Issue by Apoxiosis** [Luxocracy/TidyPlatesContinued#23]
Hey Luxo, I got the version with the previous fix and it seems to be working and happening a lot less but i've noticed some issues still. In a lot of cases, mobs spawned from other mons appear as unknown. The world boss in arathi spawns about 7 mobs who all show as Unknown, as well as many of the rare spawns in arathi still showing as unknown.

Just thought I'd mention it.

**Comment by Luxocracy** [comment]
After looking into this some more I found out there is a better way to handle these types of units.
I released a [new version](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.7b) that changes how they were handled. 

But, I doubt it will make much of a difference, if any. But at the very least I am fairly sure now that the "Unknown" name, as well as other info, will be changed to the correct info as soon as it is available from the server, rather than having the addon constantly check if the info exists.

**Comment by Apoxiosis** [comment]
I grabbed the update, will see if it worked. I noticed the nameplate view distance was set to 100. I dropped it back to default 60 to see if it would help as well but it didn't Will keep you informed.

Do you have an easier/more preferred method of communication? Discord pms or something?

**Comment by Shimiya** [comment]
Last update settled "Nameplate distance" to "10"

**Comment by Luxocracy** [comment]
There was no way of avoiding that really, made some changes to how sliders work so it would display the actual number instead of %.
The % sliders use decimals, as in 0.6 = 60%, while the ones that display actual numbers would be 60. So your settings would say the slider was set to 0.6, but the lowest it can go is 10.

Sorry for the inconvenience this caused.

**Comment by Shimiya** [comment]
The problem is the TidyPlates profile system (even before * Continued).
Despite the fact that all my characters use the same profile, I have to reapply "Load Template" on all these at every change I make, unlike the standard profile system of other addons (I do not understand why besides, since I only use one template).

**Comment by Luxocracy** [comment]
Not sure, that is actually a pretty good quick fix for the profile system. Wanted to make it a proper profile system since the start but it's a bit more of an undertaking.
But now since the original dev is back I feel like it's up to him whether or not he wants to do something about it.

**Comment by Shimiya** [comment]
He comes back after 2 years of absence and does not give you the rights ?

It's sad.

What will you do with *Continued ?

**Comment by Luxocracy** [comment]
I haven't actually talked with him about any of it. I've only mentioned that he may implement or merge anything from this project. And it doesn't feel right to continue on when the original addon is getting updated.

But I'll probably leave this project up as long as the original author doesn't have an issue with it, but I doubt I will add any more features.

**Comment by Shimiya** [comment]
Apart from the profile system, without a personal need for very specific feature or an eventual change in the Blizzard's API, TPC is perfect like that
