### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by yishuangfrank** [Luxocracy/TidyPlatesContinued#25]
Thanks for taking over this great addon and adding so many wonderful functions!

Could you add a function that we can customize the coulor for some special mob?

**Comment by yishuangfrank** [comment]
Like Spawn of G'huun

**Comment by Luxocracy** [comment]
I'm not really considering adding any new features to the project for now, as the original developers have returned, so I believe your [feature request](https://github.com/Binbwen/tidyplates/issues) would be better directed towards them.

But being able to set colors to specific units would be a neat feature to have.

**Comment by yishuangfrank** [comment]
Thanks for your reply.
I really like the new features you added.

**Comment by lucifa42** [comment]
This WeakAura makes the nameplate glow for Spawn of G'huun. Works with Tidyplates.

https://wago.io/HyoI49iV7

**Comment by yishuangfrank** [comment]
I changed the file:TidyPlatesContinuedHub\functions\color.lua
Added some codes like this:

local n = unit.name
if n == "Spawn of G'huun" or n == "Explosive"  then 
    return LocalVars.ColorPartyAggro
end

for i = 1,10 do 
 local d = select(10,UnitBuff(unit.unitid,i))
 if d == 277242 then
  return LocalVars.ColorPartyAggro
 end 
end

**Comment by Luxocracy** [comment]
I've basically added this to the [latest release](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.9).
I took a while because I was unsure of how to implement it into the settings panel properly, but I believe the current method should do just fine.

It does however only allow coloring of health bars based on the unit name.

I felt that coloring by buffs/debuffs wasn't necessary as you can already track any aura you want with the Aura Widget. And if further distinction between auras were to become necessary, it would be better add this coloration method to auras as well.

**Comment by yishuangfrank** [comment]
If lots of mobs get together at the same time,
I can't  select the right nameplate according to the buff/debuff's icons/
It bothers me for a long time.

**Comment by yishuangfrank** [comment]
thanks for the updating very much!

**Comment by Luxocracy** [comment]
So I guess I kinda changed my mind on only coloring by unit name and decided to expand upon this feature in the [latest release](https://github.com/Luxocracy/TidyPlatesContinued/releases/tag/6.21.10).

It now includes the ability to color by unit buffs as well as their health threshold, as I felt the current health threshold system was a bit limited.

**Comment by yishuangfrank** [comment]
Great!
